### ISSUE TITLE
Consider moving to ocaml-community

### ISSUE THREAD

**Issue by rizo** [ocaml-community/awesome-ocaml#147]
Now that we have a [community organization](https://github.com/ocaml-community) I think it makes sense to move this project there. It will benefit from more consistent exposure and potentially attract more contributors.

I've also proposed this for [ocamlverse.github.io](https://github.com/OCamlverse/ocamlverse.github.io/issues/59).

**Comment by rizo** [comment]
Mentioning people listed as contributors for feedback: @gasche, @Drup, @Engil and @MassD.

**Comment by rizo** [comment]
I think GitHub adds a redirect for the previous location of the project, so this transition wouldn't break existing links to awesome-ocaml.

**Comment by gasche** [comment]
I think this is a good idea.

**Comment by rizo** [comment]
I submitted the project for review: https://github.com/ocaml-community/meta/issues/23

**Comment by XVilka** [comment]
Can be closed obviously
