### ISSUE TITLE
Fix Amazon link to More OCaml Algorithms Methods Diversions book

### ISSUE THREAD

**Issue by XVilka** [ocaml-community/awesome-ocaml#179]
```
Issues :-(
> Links 
  1. [L112] 503 https://www.amazon.com/More-OCaml-Algorithms-Methods-Diversions/dp/0957671113/  
```

**Comment by kanishka-work** [comment]
This fails for me when using wget or curl, because Amazon probably checks user agent, but it works fine in a browser. Also, the latest report doesn't note this as a failure any more.

**Comment by gasche** [comment]
Thanks for the investigation! Let's be optimistic and assume that the issue is fixed. If it arises again, maybe we should look for a different URL for the book.
