### ISSUE TITLE
Fix OCaml + Cordova = more secured, typed and hybrid mobile applications

### ISSUE THREAD

**Issue by jerben** [ocaml-community/awesome-ocaml#182]
```
  3. [L387]  https://blog.danny-willems.be/en/ocaml-cordova-secured-typed-hybrid-mobile-applications/ Net::ReadTimeout 
```

**Comment by dannywillems** [comment]
Thanks for the report. I am moving my blog to dannywillems.github.io.
New link https://dannywillems.github.io/2016/07/14/ocaml-cordova-secured-typed-hybrid-mobile-applications.html.
