### ISSUE TITLE
possibly move SOTU content to ocaml homepage

### ISSUE THREAD

**Issue by kanishka-work** [ocaml-community/awesome-ocaml#188]
Library authors in various domains have ready knowledge in how thorough their library and similar libraries are in solving a given domain problem. Fund them each for a few hours every few months to make edits and updates to SOTU

**Comment by gasche** [comment]
I'm not sure to whom the question is directed (ocaml-community itself has no money and no funding structure), but I received this suggestion in an email and I will answer it from the OCaml Foundation perspective: yes, in theory we could do that, but in practice the amount of work required to give a small amount of money to many different people would be prohibitive. Maybe other organizations can do this better, but I suspect that asking one person to review and update the SOTU would be easier for most funders.

**Comment by kanishka-work** [comment]
I will try to individual contributor funding approach to start, and if that hits a wall of complexity, as you rightly suspect, will fall back to just rotating one person per year, maybe just update their section or update full document. Will note some good matches of library developers to sections below, and follow up with people offline after that.

**Comment by kanishka-work** [comment]
Recent experts:
Testing: gildor47 (ounit), craigfe (alcotest)
Data formats: leonidas-from-xiv (yojson), sexplib (xclerc)
User interfaces: dbuenzli (cmdliner)
System interaction: gildor47 (fileutils), ygrek (extunix), rjones redhat (libvirt)
Database: craigfe (ormond), mmottl (sqlite3-ocaml), darioteixera (pgocaml)

**Comment by kanishka-work** [comment]
Another way to approach this could be tag natural discussions on discuss.ocaml.org as "sotu" as well as the relevant ecosystem area that is being discussed such as "data formats" and then simply provide links to discuss.ocaml.org filtered by the tags in the sotu page. This could remove any need duplicating and curating the content here.

**Comment by kanishka-work** [comment]
I am thinking this content should move to the bottom of the ocaml homepage. That will solve the problem of getting updates as address some other issues like keeping people informed of community projects and recruiting new volunteers to working groups

**Comment by kanishka-work** [comment]
I will close this issue for now. I can reopen in a year or two, if there is a more pressing community need to match volunteers with projects or present a unified snapshot of the ocaml ecosystem to ocaml newcomers or people shopping for a programming language
