### ISSUE TITLE
shutdown, move to ocamlverse?

### ISSUE THREAD

**Issue by kanishka-work** [ocaml-community/awesome-ocaml#195]
Thinking about the duplication of content and the ability to curate and organize the content more easily with a structure like ocamlverse, I think it would help beginners more if we shut down this site, replaced it with a link to ocamlverse, and migrated all content to ocamlverse pages

**Comment by antwgames** [comment]
Don't mind me, but I love the simplicity of "awesome lists" like this one. In any case, thank you to everyone who contributed this lovely space!

**Comment by kanishka-work** [comment]
Okay if someone finds it useful, then should keep it
