### ISSUE TITLE
Problems compiling OCaml compiler when using Swedish locale

### ISSUE THREAD

**Issue by anders-hig-jackson** [ocaml-community/awesome-ocaml#205]
I have posted bug report to `OCaml` and `opam`, as I thing the bug is in OCaml, but it would be beneficial for all users if `opam` also addresses this problem.  Yes, it also shows when compiling `OCaml` from GitHub source.

It could also be good if it was noticed here, in some proper way.  And yes, it could potential be a problem for other locales too.

So, if one uses Swedish locale, and tries to create a new switch, like `opam switch create 4.12.0`, the linking stage of the compiler fails.  This because the buildning system of Ocaml (and potentially other software too) depends on ordering characters according to locale `C`, not `sv_SE.UTF-8` or other locales.  In this case, the problem is shown by Swedish locale, because of the `w` character is considered special.

A solution is to set environment variable `LC_COLLATE` to `C` ans `LC_ALL` to nothing, "", before creating the switch.  So in a shell (Bourne Shell type, like `bash`(1)), do the following.

    export LC_ALL=""
    export LC_COLLATE=C
    locale # to check that LC_COLLATE is set to C
    opam create switch 4.12.0

And now it should work.

This would have saved me weeks if I known, so I think it would been good to seen this here, in some way.

**Comment by ichingking** [comment]
`Guten Tag.`

Maybe you need post this problem to 

[OCaml  Repo](https://github.com/ocaml/ocaml)

or 

[OPAM Repo](https://github.com/ocaml/opam)

Those are `Offical Repo`.

**Comment by anders-hig-jackson** [comment]
I have posted there too, and it has resulted in a Patch.  

But as the bug made OCaml useless for me, until the fix, I thought it might have been a good place to also have information about the problem posted here to.  Might have been the wrong place.

**Comment by gasche** [comment]
I will close the ticket because I think that it indeed is not the best place for this content (awesome-ocaml is not particularly about the compiler itself or trying to do user support). But thanks for the report(s) anyway; it's a tricky issue to track down, and I am glad that the upstream compiler has since fixed it -- the fix should be available in the next released version, probably 4.13.
