### ISSUE TITLE
Add betterOCaml to the list of the online compiler available

### ISSUE THREAD

**Issue by Butanium** [ocaml-community/awesome-ocaml#209]
BetterOCaml is an online compiler which looks wonderful and is very useful for learning purpose and more.
It's available at [betterocaml.ml](betterocaml.ml).
You can check the github repo here : https://github.com/jbdoderlein/BetterOCaml

**Comment by gasche** [comment]
Sure, could you propose a Pull Request to make the change?

**Comment by Butanium** [comment]
Sure !

**Comment by gasche** [comment]
Closed by your PR #210. Thanks!
