### ISSUE TITLE
Scientific software using ocaml

### ISSUE THREAD

**Issue by RCHG** [ocaml-community/awesome-ocaml#222]
Hello. Thanks for this awesome-ocaml

There is an scientific software named WHIZARD that uses OCaml (a combination of ocaml and fortran)

https://whizard.hepforge.org/

Just in case it is useful for the list.

**Comment by rizo** [comment]
Thanks added in https://github.com/ocaml-community/awesome-ocaml/commit/23319790c15e6a4593cceee79fd3c5e6d9292b67.
